title: "c.r. hall — written works"
description: "poems, stories, etc."
url: "https://crhall-writing.github.io"
baseurl: ""
permalink: pretty
timezone: America/Chicago
future: false

theme: minima
minima:
  skin: classic
  date_format: "%-d %b %Y"
  social_links:
    - platform: github
      user_url: https://github.com/crhall-writing

header_pages:
  - stories.md
  - poems.md
  - about.md

collections:
  poems:
    output: true
    permalink: /poems/:title/
  stories:
    output: true
    permalink: /stories/:title/
  scripts:
    output: true
    permalink: /scripts/:title/

defaults:
  - scope: { path: "", type: poems }
    values:
      layout: poem
      sitemap: true
  - scope: { path: "", type: stories }
    values:
      layout: story
      sitemap: true
  - scope: { path: "", type: scripts }
    values:
      layout: script
      sitemap: true
  - scope: { path: "" }
    values:
      lang: en
      toc: false

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  footnote_backlink: "↩︎"

sass:
  style: compressed

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - .github/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

feed:
  collections:
    - poems
    - stories
