title: "c.r. hall — written works"
description: "poems, stories, etc."
url: "https://crhall-writing.github.io"
theme: minima

minima:
  skin: classic
  social_links:
    - platform: github
      user_url: https://github.com/crhall-writing

plugins:
  - jekyll-feed
  - jekyll-sitemap

future: false
timezone: America/Chicago

collections:
  poems:
    output: true
    permalink: /poems/:title/
  stories:
    output: true
    permalink: /stories/:title/
defaults:
  - scope: { path: "", type: poems }
    values: { layout: poem, nav_weight: 2 }
  - scope: { path: "", type: stories }
    values: { layout: story, nav_weight: 1 }
